### ISSUE TITLE
Error Receiving Sensor Data

### ISSUE THREAD

**Issue by Plungestep** [rsnodgrass/pysensorpush#4]
Everything appears to be working except receiving actual sensor data.  This is the error received:

    <bound method PySensorPush.samples of <PySensorPush: me@email.com>>

where my email address is correctly listed in the actual output.

**Comment by dairiki** [comment]
Despite what the README and the example say, it appears that [`PySensorPush.samples`][1] is a method, not a property.

Instead of just accessing the attribute
```
sensorpush.samples
```
try something like
```
sensorpush.samples(10)
```

(Where 10 is the value for the parameter `limit` that specifies how many samples to return.)


[1]: https://github.com/rsnodgrass/pysensorpush/blob/846b7cb99d799c434c7cf77eba3fed071371d1c7/pysensorpush/__init__.py#L172

**Comment by Plungestep** [comment]
This works!
